{
  "formatVersion": "1.1",
  "component": {
    "group": "com.octetproof",
    "module": "libpf",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "libpf-1.2.1.aar",
          "url": "libpf-1.2.1.aar",
          "size": 7052678,
          "sha512": "0eac42d9c95a4fe4a89f8879dae714b68f443778e19a1d5fc620229f4c170728334c866dc303fd74587e6ad851abbf84a710397eba0ef497861fe9663b444b59",
          "sha256": "0a718c16cf0d5ef41967bbb568d103e366c991596be5f4f74058aaa2c75ad5f3",
          "sha1": "e7b9193f7ae35b71cae66baf05f6b24c676d793c",
          "md5": "aaa74d9c3f6eec7d8e0529a289a015d1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "libpf-1.2.1.aar",
          "url": "libpf-1.2.1.aar",
          "size": 7052678,
          "sha512": "0eac42d9c95a4fe4a89f8879dae714b68f443778e19a1d5fc620229f4c170728334c866dc303fd74587e6ad851abbf84a710397eba0ef497861fe9663b444b59",
          "sha256": "0a718c16cf0d5ef41967bbb568d103e366c991596be5f4f74058aaa2c75ad5f3",
          "sha1": "e7b9193f7ae35b71cae66baf05f6b24c676d793c",
          "md5": "aaa74d9c3f6eec7d8e0529a289a015d1"
        }
      ]
    }
  ]
}
